
#服务器的相关配置，如服务的端口
server:  
    port: 8090  
    session-timeout: 30  
    tomcat.max-threads: 450  
    tomcat.uri-encoding: UTF-8
  
  
 
#服务器相关应用的相关配置，如应用的应用名，应用的端口，应用的启动入口 
application:
  server-name: gome-store-server    
  server-port: 8082
  server-launcher: com.gome.store.ServerBootstrap





#spring相关配置 
spring:
    application:
          name: qndl-web-server
    datasource:  
       name: mydb  
       type: com.alibaba.druid.pool.DruidDataSource  
       url: jdbc:oracle:thin:@10.20.100.16:1521:orcl
       username: dwuser
       password: dwDW5678
       driver-class-name: oracle.jdbc.driver.OracleDriver
       minIdle: 1  
       maxActive: 2  
       initialSize: 1  
       timeBetweenEvictionRunsMillis: 3000  
       minEvictableIdleTimeMillis: 300000  
       validationQuery: select 'x'  
       testWhileIdle: true  
       testOnBorrow: false  
       testOnReturn: false
    redis:
      timeOutType: 'hour'
      pool:
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0
      cluster:
        nodes[0]: 10.128.31.97:6373
        nodes[1]: 10.128.31.97:6374
        nodes[2]: 10.128.31.97:6375
        nodes[3]: 10.128.31.97:6376
        nodes[4]: 10.128.31.97:6377
        nodes[5]: 10.128.31.97:6378
       
##mybatise配置    
mybatis:
  mapperLocations: com/gome/store/mapper/*.xml
  typeAliasesPackage: com.gome.store.entity
  configLocation: mybatis-config.xml

  
  
  